declare module '@editorjs/raw';
declare module '@editorjs/simple-image';
declare module '@editorjs/checklist';
declare module '@editorjs/embed';
declare module '@editorjs/list';
declare module '@editorjs/quote';
declare module '@editorjs/paragraph';
declare module '@editorjs/table';
declare module '@editorjs/code';
declare module '@editorjs/header';
declare module "@/styles/globals.css"